version: '3.7'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/ikandars/gallery-app:v0.0.1
    ports:
      - 9000
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    environment:
      - APP_NAME=gallery-app
      - APP_ENV=local
      - APP_KEY=base64:3yL+zLOr9kAxWaEKh2osBuEIJaeT0NHg6GWOZI5ZDL0=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=gallery_app
      - DB_USERNAME=gallery-app
      - DB_PASSWORD=gallery-app
      - QUEUE_CONNECTION=sync
      - MINIO_KEY=gallery-app
      - MINIO_SECRET=gallery-app
      - MINIO_IMAGE_BUCKET=photos
      - FILESYSTEM_DRIVER=s3
      - STORAGE_HOST=http://minio:9001
      - AWS_ACCESS_KEY_ID=gallery-app
      - AWS_SECRET_ACCESS_KEY=gallery-app
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=photos
      - AWS_USE_PATH_STYLE_ENDPOINT=true
      - AWS_ENDPOINT=http://localhost:9001

  nginx:
    image: nginx:1.13-alpine-perl
    ports:
      - 8070:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mariadb:
    image: mariadb:10.6.3
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3304:3306
    environment:
      - MYSQL_DATABASE=gallery_app
      - MYSQL_USER=gallery-app
      - MYSQL_PASSWORD=gallery-app
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/var/lib/mysql

  minio:
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9001:9000
    environment:
      - MINIO_ACCESS_KEY=gallery-app
      - MINIO_SECRET_KEY=gallery-app
      - MINIO_DEFAULT_BUCKETS=photos

volumes:
  mariadb_data:
  minio_data:

