version: '3.7'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/ikandars/kubernetes-for-php-developers:latest
    ports:
      - 9000
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    environment:
      - APP_NAME=kubernetes-for-php-developers
      - APP_ENV=local
      - APP_KEY=base64:98Q3Q0M+x/bkN6gAJKsx7hrDsaAwdPGOP/4Jr4UybMA=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=k8s4php
      - DB_USERNAME=k8s4php
      - DB_PASSWORD=k8s4php
      - QUEUE_CONNECTION=sync
      - MINIO_KEY=k8s4php
      - MINIO_SECRET=k8s4php
      - MINIO_IMAGE_BUCKET=photos
      - FILESYSTEM_DRIVER=minio
      - STORAGE_HOST=http://minio:9001

  nginx:
    image: nginx:1.13-alpine-perl
    ports:
      - 8070:80
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mariadb:
    image: mariadb:10.6.3
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3304:3306
    environment:
      - MYSQL_DATABASE=k8s4php
      - MYSQL_USER=k8s4php
      - MYSQL_PASSWORD=k8s4php
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/var/lib/mysql

  minio:
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9001:9000
    environment:
      - MINIO_ACCESS_KEY=k8s4php
      - MINIO_SECRET_KEY=k8s4php
      - MINIO_DEFAULT_BUCKETS=photos

volumes:
  mariadb_data:
  minio_data:

